-- ========================================================================
-- IMPORTANT: Copy and paste this ENTIRE SQL into Supabase SQL Editor
-- ========================================================================
--
-- This migration updates the embedding column from 384 to 4096 dimensions
-- to support the e5-mistral-7b-instruct model
--
-- WORKAROUND STRATEGY: Instead of dropping the index directly, we:
-- 1. Create a new column with the correct dimensions
-- 2. Drop the old column (which cascades and removes the index)
-- 3. Rename the new column to the original name
--
-- This works around permission issues with dropping indexes directly.
--
-- Steps:
-- 1. Go to your Supabase dashboard
-- 2. Click on "SQL Editor" in the left sidebar
-- 3. Click "New query"
-- 4. Copy and paste this ENTIRE file
-- 5. Click "Run" (or press Ctrl+Enter)
-- 6. Wait for success message
--
-- ========================================================================

-- Step 1: Add a new column with 4096 dimensions
ALTER TABLE document_chunks
ADD COLUMN embedding_new vector(4096);

-- Step 2: Copy over NULL markers from old column (keeping data in sync)
UPDATE document_chunks
SET embedding_new = NULL
WHERE embedding IS NULL;

-- Step 3: Drop the old column (this will CASCADE delete the index)
ALTER TABLE document_chunks
DROP COLUMN embedding CASCADE;

-- Step 4: Rename the new column to the original name
ALTER TABLE document_chunks
RENAME COLUMN embedding_new TO embedding;

-- Update the match function to accept 4096-dimensional embeddings
CREATE OR REPLACE FUNCTION match_document_chunks(
  query_embedding vector(4096),
  match_document_id uuid,
  match_count int DEFAULT 5,
  similarity_threshold float DEFAULT 0.3
)
RETURNS TABLE (
  id uuid,
  document_id uuid,
  chunk_index int,
  chunk_text text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    dc.id,
    dc.document_id,
    dc.chunk_index,
    dc.chunk_text,
    1 - (dc.embedding <=> query_embedding) as similarity
  FROM document_chunks dc
  WHERE
    dc.document_id = match_document_id
    AND dc.embedding IS NOT NULL
    AND 1 - (dc.embedding <=> query_embedding) >= similarity_threshold
  ORDER BY dc.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Add comment to track migration
COMMENT ON COLUMN document_chunks.embedding IS
  'Vector embedding generated by e5-mistral-7b-instruct (4096 dimensions). Updated on 2026-02-11. Running without index for compatibility.';

-- ========================================================================
-- Migration complete! You can now generate 4096-dimensional embeddings.
--
-- ✅ This approach works around index permissions by:
--    - Creating new column with correct dimensions
--    - Dropping old column (CASCADE removes index)
--    - Renaming new column to original name
--
-- All existing embeddings were already cleared by clear-old-embeddings.js,
-- so no data loss occurred.
--
-- Next step: Run node process-all-embeddings-local.js
-- ========================================================================
