/**
 * Life Event Templates - Config-driven definitions for the Readiness Engine.
 *
 * To add a new event, add an entry to LIFE_EVENT_TEMPLATES below.
 * No code changes are needed anywhere else.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface IntakeQuestion {
  id: string;
  label: string;
  type: 'select' | 'boolean';
  options?: { value: string; label: string }[];
  /** If present, the answer to this question controls which requirements are applicable */
  controlsRequirements?: string[];
}

export interface RequirementValidation {
  /** If true, the doc must not be expired */
  notExpired?: boolean;
  /** If true, a warning is shown when doc expires within 90 days */
  warnExpiringSoon?: boolean;
  /** Metadata fields that must be present on the document */
  requiredMetadata?: string[];
}

export interface EventRequirement {
  id: string;
  title: string;
  description: string;
  section: EventSection;
  /** Document categories (from the documents table) that can satisfy this */
  docCategories: string[];
  /** Specific tags that help narrow down the match */
  suggestedTags: string[];
  /** Keywords to look for in filename or extracted text (heuristic pass) */
  keywords: string[];
  validation: RequirementValidation;
  /** Weight for scoring (default 1) */
  weight: number;
  /** Requirement IDs that must be completed first */
  dependencies?: string[];
  /**
   * Conditions under which this requirement is not applicable.
   * Keys are intake question IDs, values are the answer that makes it N/A.
   */
  notApplicableWhen?: Record<string, string>;
}

export type EventSection =
  | 'Identity'
  | 'Financial'
  | 'Insurance'
  | 'Property'
  | 'Legal'
  | 'Health'
  | 'Education'
  | 'Travel'
  | 'Logistics'
  | 'Business';

export interface LifeEventTemplate {
  id: string;
  name: string;
  description: string;
  icon: string; // lucide icon name
  intakeQuestions: IntakeQuestion[];
  requirements: EventRequirement[];
}

// ---------------------------------------------------------------------------
// Templates
// ---------------------------------------------------------------------------

export const LIFE_EVENT_TEMPLATES: LifeEventTemplate[] = [
  // =========================================================================
  // 1) Moving
  // =========================================================================
  {
    id: 'moving',
    name: 'Moving',
    description: 'Prepare all documents you need when relocating — whether across town or across the country.',
    icon: 'Truck',
    intakeQuestions: [
      {
        id: 'move_type',
        label: 'Where are you moving to?',
        type: 'select',
        options: [
          { value: 'within_state', label: 'Within the same state' },
          { value: 'out_of_state', label: 'Different state' },
          { value: 'out_of_country', label: 'Another country' },
        ],
      },
      {
        id: 'housing_type',
        label: 'Will you be renting or buying at your new location?',
        type: 'select',
        options: [
          { value: 'renting', label: 'Renting' },
          { value: 'owning', label: 'Buying / Owning' },
        ],
      },
      {
        id: 'has_vehicle',
        label: 'Do you have a vehicle that needs to be transferred?',
        type: 'boolean',
      },
      {
        id: 'has_school_children',
        label: 'Do you have school-age children?',
        type: 'boolean',
      },
      {
        id: 'has_pets',
        label: 'Do you have pets?',
        type: 'boolean',
      },
    ],
    requirements: [
      {
        id: 'moving-id',
        title: 'Government-Issued ID',
        description: 'Valid driver\'s license or state ID. Out-of-state and international moves require updating this at your new location.',
        section: 'Identity',
        docCategories: ['other'],
        suggestedTags: ['id', 'driver-license', 'state-id', 'identity'],
        keywords: ['driver', 'license', 'state id', 'identification', 'id card'],
        validation: { notExpired: true, warnExpiringSoon: true },
        weight: 2,
      },
      {
        id: 'moving-passport',
        title: 'Valid Passport',
        description: 'Required for international moves. Must be valid for at least 6 months beyond your move date.',
        section: 'Identity',
        docCategories: ['other'],
        suggestedTags: ['passport', 'identity'],
        keywords: ['passport'],
        validation: { notExpired: true, warnExpiringSoon: true },
        weight: 3,
        notApplicableWhen: { move_type: 'within_state' },
      },
      {
        id: 'moving-lease',
        title: 'Current Lease or Mortgage Statement',
        description: 'Your current lease agreement or mortgage statement for move-out reference and deposit recovery.',
        section: 'Property',
        docCategories: ['lease', 'contract'],
        suggestedTags: ['lease', 'mortgage', 'rental-agreement'],
        keywords: ['lease', 'rental agreement', 'mortgage', 'deed'],
        validation: {},
        weight: 1,
      },
      {
        id: 'moving-new-lease',
        title: 'New Lease Agreement',
        description: 'Signed lease for your new rental residence.',
        section: 'Property',
        docCategories: ['lease', 'contract'],
        suggestedTags: ['new-lease', 'rental-agreement'],
        keywords: ['new lease', 'rental agreement', 'new rental'],
        validation: {},
        weight: 2,
        notApplicableWhen: { housing_type: 'owning' },
      },
      {
        id: 'moving-purchase-agreement',
        title: 'Purchase Agreement / Closing Docs',
        description: 'Signed purchase contract or closing documents for your new home.',
        section: 'Property',
        docCategories: ['contract'],
        suggestedTags: ['purchase-agreement', 'closing', 'new-home'],
        keywords: ['purchase agreement', 'closing', 'settlement', 'deed'],
        validation: {},
        weight: 2,
        notApplicableWhen: { housing_type: 'renting' },
      },
      {
        id: 'moving-insurance-renters',
        title: 'Renters Insurance Policy',
        description: 'Proof of renters insurance for your new address. Most landlords require this before move-in.',
        section: 'Insurance',
        docCategories: ['insurance'],
        suggestedTags: ['renters-insurance', 'insurance'],
        keywords: ['renters insurance', 'tenant insurance', 'renter'],
        validation: { notExpired: true, warnExpiringSoon: true },
        weight: 1,
        notApplicableWhen: { housing_type: 'owning' },
      },
      {
        id: 'moving-insurance-home',
        title: 'Homeowners Insurance Policy',
        description: 'Insurance policy for your new property. Required before closing on most mortgages.',
        section: 'Insurance',
        docCategories: ['insurance'],
        suggestedTags: ['homeowners-insurance', 'home-insurance'],
        keywords: ['homeowners insurance', 'home insurance', 'property insurance'],
        validation: { notExpired: true, warnExpiringSoon: true },
        weight: 2,
        notApplicableWhen: { housing_type: 'renting' },
      },
      {
        id: 'moving-utility',
        title: 'Utility Setup Confirmation',
        description: 'Confirmation of utility transfers or new account setup (electric, gas, water, internet).',
        section: 'Logistics',
        docCategories: ['other', 'contract'],
        suggestedTags: ['utility', 'electric', 'gas', 'water', 'internet'],
        keywords: ['utility', 'electric', 'gas', 'water', 'internet', 'cable'],
        validation: {},
        weight: 1,
      },
      {
        id: 'moving-employment',
        title: 'Employment Verification / Pay Stubs',
        description: 'Recent pay stubs or employment letter. Often required by landlords or mortgage lenders.',
        section: 'Financial',
        docCategories: ['employment'],
        suggestedTags: ['pay-stub', 'employment-letter', 'income'],
        keywords: ['pay stub', 'employment', 'income', 'salary', 'verification'],
        validation: {},
        weight: 1,
      },
      {
        id: 'moving-vehicle-reg',
        title: 'Vehicle Registration & Title',
        description: 'Current vehicle registration and title. Must be updated when moving to a new state.',
        section: 'Identity',
        docCategories: ['other'],
        suggestedTags: ['vehicle', 'registration', 'car', 'title'],
        keywords: ['vehicle registration', 'car registration', 'auto registration', 'car title'],
        validation: { notExpired: true },
        weight: 1,
        notApplicableWhen: { has_vehicle: 'false' },
      },
      {
        id: 'moving-auto-insurance',
        title: 'Auto Insurance Policy',
        description: 'Current auto insurance policy. Needs to be updated with your new address and potentially new state minimums.',
        section: 'Insurance',
        docCategories: ['insurance'],
        suggestedTags: ['auto-insurance', 'car-insurance'],
        keywords: ['auto insurance', 'car insurance', 'vehicle insurance'],
        validation: { notExpired: true, warnExpiringSoon: true },
        weight: 1,
        notApplicableWhen: { has_vehicle: 'false' },
      },
      {
        id: 'moving-school-records',
        title: 'School Enrollment Records & Transcripts',
        description: 'Current school transcripts, immunization records, and enrollment forms for new school district.',
        section: 'Education',
        docCategories: ['other'],
        suggestedTags: ['school', 'transcript', 'enrollment', 'education'],
        keywords: ['school', 'transcript', 'enrollment', 'education', 'grade', 'report card'],
        validation: {},
        weight: 2,
        notApplicableWhen: { has_school_children: 'false' },
      },
      {
        id: 'moving-pet-records',
        title: 'Pet Vaccination & Vet Records',
        description: 'Up-to-date vaccination records and veterinary history. Many apartments require proof of vaccinations.',
        section: 'Health',
        docCategories: ['other'],
        suggestedTags: ['pet', 'vaccination', 'veterinary'],
        keywords: ['pet', 'vaccination', 'veterinary', 'vet', 'rabies', 'animal'],
        validation: {},
        weight: 1,
        notApplicableWhen: { has_pets: 'false' },
      },
      {
        id: 'moving-mail-forwarding',
        title: 'Mail Forwarding Confirmation',
        description: 'USPS mail forwarding confirmation or change of address receipt.',
        section: 'Logistics',
        docCategories: ['other'],
        suggestedTags: ['mail', 'forwarding', 'address-change'],
        keywords: ['mail forwarding', 'change of address', 'usps', 'postal'],
        validation: {},
        weight: 1,
      },
    ],
  },

  // =========================================================================
  // 2) International Travel
  // =========================================================================
  {
    id: 'international-travel',
    name: 'International Travel',
    description: 'Ensure all travel documents are ready before your trip abroad.',
    icon: 'Plane',
    intakeQuestions: [
      {
        id: 'destination_region',
        label: 'What region are you traveling to?',
        type: 'select',
        options: [
          { value: 'schengen', label: 'Schengen Area (EU)' },
          { value: 'uk', label: 'United Kingdom' },
          { value: 'asia_pacific', label: 'Asia-Pacific' },
          { value: 'americas', label: 'Americas (non-US)' },
          { value: 'africa_middle_east', label: 'Africa / Middle East' },
        ],
      },
      {
        id: 'trip_length',
        label: 'How long is your trip?',
        type: 'select',
        options: [
          { value: 'short', label: 'Under 2 weeks' },
          { value: 'medium', label: '2–4 weeks' },
          { value: 'extended', label: 'Over a month' },
        ],
      },
      {
        id: 'traveling_with_kids',
        label: 'Are you traveling with children under 18?',
        type: 'boolean',
      },
      {
        id: 'has_medical_needs',
        label: 'Do you have medical conditions or take prescription medications?',
        type: 'boolean',
      },
      {
        id: 'will_drive_abroad',
        label: 'Will you be renting a car or driving abroad?',
        type: 'boolean',
      },
    ],
    requirements: [
      {
        id: 'travel-passport',
        title: 'Valid Passport',
        description: 'Must be valid for at least 6 months beyond your travel dates. Check for sufficient blank pages.',
        section: 'Identity',
        docCategories: ['other'],
        suggestedTags: ['passport', 'identity'],
        keywords: ['passport'],
        validation: { notExpired: true, warnExpiringSoon: true },
        weight: 3,
      },
      {
        id: 'travel-visa',
        title: 'Visa or Entry Authorization',
        description: 'Entry visa, eVisa, or electronic travel authorization for your destination country.',
        section: 'Travel',
        docCategories: ['other'],
        suggestedTags: ['visa', 'travel-visa', 'eta', 'esta'],
        keywords: ['visa', 'entry permit', 'travel authorization', 'esta', 'eta'],
        validation: { notExpired: true },
        weight: 2,
        notApplicableWhen: { destination_region: 'schengen' },
      },
      {
        id: 'travel-insurance',
        title: 'Travel Insurance Policy',
        description: 'Comprehensive travel insurance covering medical emergencies, trip cancellation, and lost luggage.',
        section: 'Insurance',
        docCategories: ['insurance'],
        suggestedTags: ['travel-insurance', 'health-insurance'],
        keywords: ['travel insurance', 'trip insurance', 'travel health'],
        validation: { notExpired: true, warnExpiringSoon: true },
        weight: 2,
      },
      {
        id: 'travel-itinerary',
        title: 'Flight & Accommodation Itinerary',
        description: 'Booking confirmations for flights, hotels, and any pre-arranged tours or transfers.',
        section: 'Travel',
        docCategories: ['other', 'contract'],
        suggestedTags: ['itinerary', 'flight', 'booking', 'hotel'],
        keywords: ['itinerary', 'flight', 'booking', 'reservation', 'ticket', 'hotel'],
        validation: {},
        weight: 1,
      },
      {
        id: 'travel-vaccination',
        title: 'Vaccination Records / Health Certificate',
        description: 'Proof of required or recommended vaccinations for your destination (e.g., Yellow Fever, COVID-19).',
        section: 'Health',
        docCategories: ['other'],
        suggestedTags: ['vaccination', 'health', 'immunization'],
        keywords: ['vaccination', 'vaccine', 'immunization', 'health record', 'yellow fever'],
        validation: {},
        weight: 1,
      },
      {
        id: 'travel-child-consent',
        title: 'Child Travel Consent Letter',
        description: 'Notarized consent letter from the non-traveling parent for minor children crossing international borders.',
        section: 'Legal',
        docCategories: ['other', 'contract'],
        suggestedTags: ['child-travel', 'consent', 'minor'],
        keywords: ['child consent', 'minor travel', 'parental consent', 'notarized'],
        validation: {},
        weight: 2,
        notApplicableWhen: { traveling_with_kids: 'false' },
      },
      {
        id: 'travel-child-passport',
        title: 'Child Passport(s)',
        description: 'Valid passports for all children traveling. Note: child passports have shorter validity periods.',
        section: 'Identity',
        docCategories: ['other'],
        suggestedTags: ['passport', 'child-passport'],
        keywords: ['child passport', 'minor passport'],
        validation: { notExpired: true, warnExpiringSoon: true },
        weight: 2,
        notApplicableWhen: { traveling_with_kids: 'false' },
      },
      {
        id: 'travel-prescription-docs',
        title: 'Prescription Documentation',
        description: 'Letter from your doctor listing medications, dosages, and medical necessity. Some countries require this for controlled substances.',
        section: 'Health',
        docCategories: ['other'],
        suggestedTags: ['prescription', 'medical', 'medication'],
        keywords: ['prescription', 'medication', 'doctor letter', 'medical', 'controlled substance'],
        validation: {},
        weight: 2,
        notApplicableWhen: { has_medical_needs: 'false' },
      },
      {
        id: 'travel-medical-summary',
        title: 'Medical Summary / Emergency Card',
        description: 'Summary of medical conditions, allergies, and emergency contacts in the destination language.',
        section: 'Health',
        docCategories: ['other'],
        suggestedTags: ['medical-summary', 'emergency', 'health'],
        keywords: ['medical summary', 'health card', 'emergency', 'allergy', 'medical condition'],
        validation: {},
        weight: 1,
        notApplicableWhen: { has_medical_needs: 'false' },
      },
      {
        id: 'travel-idp',
        title: 'International Driving Permit',
        description: 'International Driving Permit (IDP) issued by AAA or your national automobile association. Required or recommended in most countries.',
        section: 'Travel',
        docCategories: ['other'],
        suggestedTags: ['driving-permit', 'idp', 'international-license'],
        keywords: ['international driving permit', 'idp', 'driving license', 'driving abroad'],
        validation: { notExpired: true },
        weight: 2,
        notApplicableWhen: { will_drive_abroad: 'false' },
      },
      {
        id: 'travel-return-proof',
        title: 'Proof of Onward / Return Travel',
        description: 'Return ticket or proof of onward travel. Many countries require this for entry, especially for extended stays.',
        section: 'Travel',
        docCategories: ['other'],
        suggestedTags: ['return-ticket', 'onward-travel'],
        keywords: ['return ticket', 'onward travel', 'return flight', 'departure'],
        validation: {},
        weight: 1,
        notApplicableWhen: { trip_length: 'short' },
      },
      {
        id: 'travel-embassy-registration',
        title: 'Embassy Registration / STEP Enrollment',
        description: 'Registration with your embassy or the Smart Traveler Enrollment Program (STEP) for extended travel.',
        section: 'Travel',
        docCategories: ['other'],
        suggestedTags: ['embassy', 'step', 'registration'],
        keywords: ['embassy', 'step', 'consulate', 'registration', 'enrollment'],
        validation: {},
        weight: 1,
        notApplicableWhen: { trip_length: 'short' },
      },
    ],
  },

  // =========================================================================
  // 3) New Baby
  // =========================================================================
  {
    id: 'new-baby',
    name: 'New Baby',
    description: 'Collect and organize all documents needed when welcoming a new child.',
    icon: 'Baby',
    intakeQuestions: [
      {
        id: 'birth_type',
        label: 'Where do you plan to give birth?',
        type: 'select',
        options: [
          { value: 'hospital', label: 'Hospital' },
          { value: 'birthing_center', label: 'Birthing center' },
          { value: 'home', label: 'Home birth' },
        ],
      },
      {
        id: 'add_to_insurance',
        label: 'Will you be adding the baby to your health insurance plan?',
        type: 'boolean',
      },
      {
        id: 'both_parents_on_cert',
        label: 'Will both parents be listed on the birth certificate?',
        type: 'boolean',
      },
      {
        id: 'taking_parental_leave',
        label: 'Will a parent be taking formal parental leave from work?',
        type: 'boolean',
      },
      {
        id: 'setting_up_529',
        label: 'Do you plan to set up a college savings (529) plan?',
        type: 'boolean',
      },
    ],
    requirements: [
      {
        id: 'baby-birth-cert',
        title: 'Birth Certificate',
        description: 'Official birth certificate for your child. Usually initiated at the hospital or birthing center.',
        section: 'Identity',
        docCategories: ['other'],
        suggestedTags: ['birth-certificate', 'identity', 'child'],
        keywords: ['birth certificate', 'certificate of birth'],
        validation: {},
        weight: 3,
      },
      {
        id: 'baby-ssn',
        title: 'Social Security Card',
        description: 'Social Security number application or card for the newborn. Can be applied for alongside the birth certificate.',
        section: 'Identity',
        docCategories: ['other'],
        suggestedTags: ['ssn', 'social-security', 'child'],
        keywords: ['social security', 'ssn', 'ss card'],
        validation: {},
        weight: 2,
      },
      {
        id: 'baby-health-insurance',
        title: 'Health Insurance (Updated with Dependent)',
        description: 'Health insurance policy updated to include the newborn. Most plans require adding within 30 days of birth.',
        section: 'Insurance',
        docCategories: ['insurance'],
        suggestedTags: ['health-insurance', 'dependent', 'baby'],
        keywords: ['health insurance', 'dependent', 'coverage', 'newborn'],
        validation: { notExpired: true },
        weight: 2,
        notApplicableWhen: { add_to_insurance: 'false' },
      },
      {
        id: 'baby-hospital-records',
        title: 'Hospital / Birth Center Records',
        description: 'Medical records from the birth including discharge papers, APGAR scores, and initial screenings.',
        section: 'Health',
        docCategories: ['other'],
        suggestedTags: ['hospital', 'medical', 'birth-records'],
        keywords: ['hospital', 'discharge', 'medical record', 'birth record', 'apgar'],
        validation: {},
        weight: 1,
        notApplicableWhen: { birth_type: 'home' },
      },
      {
        id: 'baby-newborn-screening',
        title: 'Newborn Screening & Hearing Test Results',
        description: 'State-mandated newborn screening results and hearing test documentation.',
        section: 'Health',
        docCategories: ['other'],
        suggestedTags: ['newborn-screening', 'hearing-test', 'medical'],
        keywords: ['newborn screening', 'hearing test', 'metabolic screen', 'heel prick'],
        validation: {},
        weight: 1,
      },
      {
        id: 'baby-pediatrician',
        title: 'Pediatrician Records',
        description: 'Selected pediatrician information and initial well-baby visit records.',
        section: 'Health',
        docCategories: ['other'],
        suggestedTags: ['pediatrician', 'doctor', 'child-health'],
        keywords: ['pediatrician', 'doctor', 'well-baby', 'child health'],
        validation: {},
        weight: 1,
      },
      {
        id: 'baby-paternity',
        title: 'Paternity Acknowledgment Affidavit',
        description: 'Voluntary Acknowledgment of Paternity form if parents are unmarried or for second parent recognition.',
        section: 'Legal',
        docCategories: ['other', 'contract'],
        suggestedTags: ['paternity', 'acknowledgment', 'legal'],
        keywords: ['paternity', 'acknowledgment', 'affidavit', 'parentage'],
        validation: {},
        weight: 2,
        notApplicableWhen: { both_parents_on_cert: 'true' },
      },
      {
        id: 'baby-parental-leave',
        title: 'FMLA / Parental Leave Documentation',
        description: 'Completed FMLA forms, employer leave approval, and short-term disability paperwork if applicable.',
        section: 'Legal',
        docCategories: ['employment', 'contract'],
        suggestedTags: ['fmla', 'parental-leave', 'maternity', 'paternity'],
        keywords: ['fmla', 'parental leave', 'maternity leave', 'paternity leave', 'family leave'],
        validation: {},
        weight: 2,
        notApplicableWhen: { taking_parental_leave: 'false' },
      },
      {
        id: 'baby-529-plan',
        title: '529 College Savings Plan Setup',
        description: 'Account opening documents for a 529 education savings plan.',
        section: 'Financial',
        docCategories: ['other'],
        suggestedTags: ['529', 'college-savings', 'education'],
        keywords: ['529', 'college savings', 'education savings', 'college fund'],
        validation: {},
        weight: 1,
        notApplicableWhen: { setting_up_529: 'false' },
      },
      {
        id: 'baby-will-update',
        title: 'Will / Guardian Designation',
        description: 'Updated will or guardianship designation including the new child. Critical for naming who cares for your child.',
        section: 'Legal',
        docCategories: ['contract', 'other'],
        suggestedTags: ['will', 'guardian', 'estate', 'legal'],
        keywords: ['will', 'guardian', 'guardianship', 'estate', 'trust'],
        validation: {},
        weight: 2,
      },
      {
        id: 'baby-life-insurance',
        title: 'Life Insurance Policy',
        description: 'Life insurance policy updated with new beneficiary or increased coverage for the growing family.',
        section: 'Insurance',
        docCategories: ['insurance'],
        suggestedTags: ['life-insurance', 'beneficiary'],
        keywords: ['life insurance', 'beneficiary', 'term life'],
        validation: { notExpired: true },
        weight: 1,
      },
      {
        id: 'baby-childcare',
        title: 'Childcare / Daycare Enrollment',
        description: 'Daycare or childcare enrollment documents, waitlist confirmation, or nanny contract.',
        section: 'Logistics',
        docCategories: ['contract', 'other'],
        suggestedTags: ['childcare', 'daycare', 'nanny'],
        keywords: ['childcare', 'daycare', 'nanny', 'babysitter', 'enrollment'],
        validation: {},
        weight: 1,
      },
    ],
  },

  // =========================================================================
  // 4) Buying a Home
  // =========================================================================
  {
    id: 'buying-home',
    name: 'Buying a Home',
    description: 'Organize all documents required for the home purchase process — from pre-approval to closing.',
    icon: 'Home',
    intakeQuestions: [
      {
        id: 'first_time_buyer',
        label: 'Is this your first home purchase?',
        type: 'boolean',
      },
      {
        id: 'financing_type',
        label: 'How are you financing?',
        type: 'select',
        options: [
          { value: 'conventional', label: 'Conventional mortgage' },
          { value: 'fha_va', label: 'FHA / VA / USDA loan' },
          { value: 'cash', label: 'All cash' },
        ],
      },
      {
        id: 'is_hoa_condo',
        label: 'Is the property part of an HOA or a condo association?',
        type: 'boolean',
      },
      {
        id: 'selling_current_home',
        label: 'Are you also selling a current home?',
        type: 'boolean',
      },
      {
        id: 'relocating_for_work',
        label: 'Are you relocating for work?',
        type: 'boolean',
      },
    ],
    requirements: [
      {
        id: 'home-id',
        title: 'Government-Issued ID',
        description: 'Valid photo ID for all signatories. Required at closing.',
        section: 'Identity',
        docCategories: ['other'],
        suggestedTags: ['id', 'driver-license', 'identity'],
        keywords: ['driver', 'license', 'id', 'identification', 'passport'],
        validation: { notExpired: true },
        weight: 2,
      },
      {
        id: 'home-preapproval',
        title: 'Mortgage Pre-Approval Letter',
        description: 'Pre-approval letter from your lender showing how much you\'re qualified to borrow.',
        section: 'Financial',
        docCategories: ['contract', 'other'],
        suggestedTags: ['pre-approval', 'mortgage', 'lender'],
        keywords: ['pre-approval', 'preapproval', 'mortgage', 'lender', 'qualified'],
        validation: {},
        weight: 2,
        notApplicableWhen: { financing_type: 'cash' },
      },
      {
        id: 'home-income-proof',
        title: 'Proof of Income (W-2s, Tax Returns, Pay Stubs)',
        description: 'Last 2 years of W-2s/tax returns plus recent pay stubs. Required by all mortgage lenders.',
        section: 'Financial',
        docCategories: ['employment'],
        suggestedTags: ['pay-stub', 'income', 'tax-return', 'w2'],
        keywords: ['pay stub', 'income', 'tax return', 'w2', 'w-2', 'employment'],
        validation: {},
        weight: 2,
        notApplicableWhen: { financing_type: 'cash' },
      },
      {
        id: 'home-bank-statements',
        title: 'Bank Statements (Last 2–3 Months)',
        description: 'Recent bank statements showing sufficient funds for down payment and closing costs.',
        section: 'Financial',
        docCategories: ['other'],
        suggestedTags: ['bank-statement', 'financial', 'savings'],
        keywords: ['bank statement', 'account statement', 'savings', 'checking'],
        validation: {},
        weight: 1,
      },
      {
        id: 'home-gift-letter',
        title: 'Gift Letter (Down Payment Assistance)',
        description: 'If any down payment funds are a gift, a signed letter from the donor is required by the lender.',
        section: 'Financial',
        docCategories: ['other', 'contract'],
        suggestedTags: ['gift-letter', 'down-payment'],
        keywords: ['gift letter', 'down payment', 'gift funds'],
        validation: {},
        weight: 1,
        notApplicableWhen: { financing_type: 'cash' },
      },
      {
        id: 'home-purchase-agreement',
        title: 'Purchase Agreement / Offer',
        description: 'Signed purchase/sale agreement for the property.',
        section: 'Property',
        docCategories: ['contract'],
        suggestedTags: ['purchase-agreement', 'home-purchase', 'contract'],
        keywords: ['purchase agreement', 'sale agreement', 'contract', 'offer'],
        validation: {},
        weight: 2,
      },
      {
        id: 'home-inspection',
        title: 'Home Inspection Report',
        description: 'Professional inspection report covering structure, electrical, plumbing, roof, and HVAC.',
        section: 'Property',
        docCategories: ['other'],
        suggestedTags: ['inspection', 'home-inspection'],
        keywords: ['inspection', 'home inspection', 'property inspection'],
        validation: {},
        weight: 1,
      },
      {
        id: 'home-appraisal',
        title: 'Appraisal Report',
        description: 'Professional appraisal to confirm the home\'s market value. Required by mortgage lenders.',
        section: 'Property',
        docCategories: ['other'],
        suggestedTags: ['appraisal', 'valuation'],
        keywords: ['appraisal', 'valuation', 'market value', 'appraised'],
        validation: {},
        weight: 1,
        notApplicableWhen: { financing_type: 'cash' },
      },
      {
        id: 'home-pest-inspection',
        title: 'Termite / Pest Inspection',
        description: 'Wood-destroying organism (WDO) inspection report. Required in many states.',
        section: 'Property',
        docCategories: ['other'],
        suggestedTags: ['pest-inspection', 'termite'],
        keywords: ['termite', 'pest', 'wdo', 'wood destroying', 'pest inspection'],
        validation: {},
        weight: 1,
      },
      {
        id: 'home-insurance',
        title: 'Homeowners Insurance Policy',
        description: 'Insurance policy for the property. Must be bound before closing.',
        section: 'Insurance',
        docCategories: ['insurance'],
        suggestedTags: ['homeowners-insurance', 'home-insurance'],
        keywords: ['homeowners insurance', 'home insurance', 'property insurance'],
        validation: { notExpired: true },
        weight: 2,
      },
      {
        id: 'home-title',
        title: 'Title Report / Title Insurance',
        description: 'Title search report confirming clear ownership and title insurance binder.',
        section: 'Legal',
        docCategories: ['other', 'contract'],
        suggestedTags: ['title', 'title-insurance', 'deed'],
        keywords: ['title', 'title insurance', 'deed', 'lien'],
        validation: {},
        weight: 2,
      },
      {
        id: 'home-hoa-docs',
        title: 'HOA / Condo Association Documents',
        description: 'CC&Rs, HOA bylaws, meeting minutes, financial statements, and any pending assessments.',
        section: 'Property',
        docCategories: ['other', 'contract'],
        suggestedTags: ['hoa', 'condo', 'ccr', 'association'],
        keywords: ['hoa', 'condo', 'ccr', 'bylaws', 'association', 'covenants'],
        validation: {},
        weight: 1,
        notApplicableWhen: { is_hoa_condo: 'false' },
      },
      {
        id: 'home-current-sale',
        title: 'Current Home Sale Agreement',
        description: 'Listing agreement and sale contract for your current home, if applicable.',
        section: 'Property',
        docCategories: ['contract'],
        suggestedTags: ['home-sale', 'listing', 'sale-agreement'],
        keywords: ['listing', 'sale agreement', 'selling', 'current home'],
        validation: {},
        weight: 1,
        notApplicableWhen: { selling_current_home: 'false' },
      },
      {
        id: 'home-relocation-package',
        title: 'Employer Relocation Package',
        description: 'Relocation agreement, reimbursement terms, and any employer-sponsored benefits.',
        section: 'Financial',
        docCategories: ['employment', 'contract'],
        suggestedTags: ['relocation', 'employer', 'reimbursement'],
        keywords: ['relocation', 'employer relocation', 'reimbursement', 'relocation package'],
        validation: {},
        weight: 1,
        notApplicableWhen: { relocating_for_work: 'false' },
      },
    ],
  },

  // =========================================================================
  // 5) Starting a Small Business
  // =========================================================================
  {
    id: 'starting-business',
    name: 'Starting a Small Business',
    description: 'Gather formation documents, licenses, and policies to launch your business the right way.',
    icon: 'Briefcase',
    intakeQuestions: [
      {
        id: 'business_structure',
        label: 'What business structure are you forming?',
        type: 'select',
        options: [
          { value: 'sole_proprietorship', label: 'Sole Proprietorship' },
          { value: 'llc', label: 'LLC' },
          { value: 'corporation', label: 'Corporation (S-Corp / C-Corp)' },
          { value: 'partnership', label: 'Partnership' },
        ],
      },
      {
        id: 'has_employees',
        label: 'Will you have employees (not just yourself)?',
        type: 'boolean',
      },
      {
        id: 'has_physical_location',
        label: 'Will you have a physical location (office, storefront, warehouse)?',
        type: 'boolean',
      },
      {
        id: 'sells_online',
        label: 'Will you sell products or services online?',
        type: 'boolean',
      },
      {
        id: 'seeking_funding',
        label: 'Do you plan to seek outside funding (investors, loans, grants)?',
        type: 'boolean',
      },
    ],
    requirements: [
      {
        id: 'biz-formation',
        title: 'Business Formation Documents',
        description: 'Articles of incorporation, LLC operating agreement, partnership agreement, or DBA registration.',
        section: 'Legal',
        docCategories: ['contract', 'other'],
        suggestedTags: ['business', 'formation', 'articles', 'llc', 'dba'],
        keywords: ['articles of incorporation', 'operating agreement', 'dba', 'formation', 'llc', 'partnership agreement'],
        validation: {},
        weight: 3,
        notApplicableWhen: { business_structure: 'sole_proprietorship' },
      },
      {
        id: 'biz-ein',
        title: 'EIN (Employer Identification Number)',
        description: 'IRS-issued EIN for your business. Required for tax filing, hiring, and opening bank accounts.',
        section: 'Financial',
        docCategories: ['other'],
        suggestedTags: ['ein', 'tax-id', 'irs'],
        keywords: ['ein', 'employer identification', 'tax id', 'irs'],
        validation: {},
        weight: 2,
      },
      {
        id: 'biz-license',
        title: 'Business License / Permits',
        description: 'Local, state, or federal business licenses and permits required for your industry.',
        section: 'Legal',
        docCategories: ['other', 'contract'],
        suggestedTags: ['business-license', 'permit'],
        keywords: ['business license', 'permit', 'operating license'],
        validation: { notExpired: true, warnExpiringSoon: true },
        weight: 2,
      },
      {
        id: 'biz-insurance',
        title: 'Business Liability Insurance',
        description: 'General liability and/or professional liability (E&O) insurance for your business.',
        section: 'Insurance',
        docCategories: ['insurance'],
        suggestedTags: ['business-insurance', 'liability'],
        keywords: ['business insurance', 'liability', 'general liability', 'professional liability', 'e&o'],
        validation: { notExpired: true, warnExpiringSoon: true },
        weight: 2,
      },
      {
        id: 'biz-bank',
        title: 'Business Bank Account',
        description: 'Proof of business bank account opening. Separate business and personal finances from day one.',
        section: 'Financial',
        docCategories: ['other'],
        suggestedTags: ['bank-account', 'business-bank'],
        keywords: ['business account', 'bank account', 'business banking'],
        validation: {},
        weight: 1,
      },
      {
        id: 'biz-tax-id-state',
        title: 'State Tax Registration',
        description: 'State sales tax permit, income tax registration, or franchise tax filing.',
        section: 'Financial',
        docCategories: ['other'],
        suggestedTags: ['tax', 'state-tax', 'sales-tax'],
        keywords: ['state tax', 'sales tax', 'tax registration', 'franchise tax'],
        validation: {},
        weight: 1,
      },
      {
        id: 'biz-employment-docs',
        title: 'Employee Documentation (W-4, I-9)',
        description: 'Employment agreements, W-4 withholding forms, I-9 verification, and employee handbook.',
        section: 'Legal',
        docCategories: ['employment', 'contract'],
        suggestedTags: ['employee', 'w4', 'i9', 'handbook'],
        keywords: ['w-4', 'w4', 'i-9', 'i9', 'employment agreement', 'employee handbook'],
        validation: {},
        weight: 2,
        notApplicableWhen: { has_employees: 'false' },
      },
      {
        id: 'biz-workers-comp',
        title: 'Workers Compensation Insurance',
        description: 'Workers comp policy. Required in most states if you have employees.',
        section: 'Insurance',
        docCategories: ['insurance'],
        suggestedTags: ['workers-comp', 'insurance'],
        keywords: ['workers compensation', 'workers comp', 'work injury'],
        validation: { notExpired: true },
        weight: 2,
        notApplicableWhen: { has_employees: 'false' },
      },
      {
        id: 'biz-commercial-lease',
        title: 'Commercial Lease Agreement',
        description: 'Signed lease for your office, retail, or warehouse space.',
        section: 'Property',
        docCategories: ['lease', 'contract'],
        suggestedTags: ['commercial-lease', 'office-lease', 'retail-lease'],
        keywords: ['commercial lease', 'office lease', 'retail space', 'warehouse'],
        validation: {},
        weight: 2,
        notApplicableWhen: { has_physical_location: 'false' },
      },
      {
        id: 'biz-zoning',
        title: 'Zoning & Use Permits',
        description: 'Zoning approval, certificate of occupancy, or use permit for your business location.',
        section: 'Legal',
        docCategories: ['other'],
        suggestedTags: ['zoning', 'permit', 'occupancy'],
        keywords: ['zoning', 'certificate of occupancy', 'use permit', 'zoning permit'],
        validation: {},
        weight: 1,
        notApplicableWhen: { has_physical_location: 'false' },
      },
      {
        id: 'biz-privacy-tos',
        title: 'Privacy Policy & Terms of Service',
        description: 'Legal documents required for any business with an online presence or that collects customer data.',
        section: 'Legal',
        docCategories: ['other', 'contract'],
        suggestedTags: ['privacy-policy', 'terms-of-service', 'legal'],
        keywords: ['privacy policy', 'terms of service', 'terms and conditions', 'tos'],
        validation: {},
        weight: 1,
        notApplicableWhen: { sells_online: 'false' },
      },
      {
        id: 'biz-business-plan',
        title: 'Business Plan & Financial Projections',
        description: 'Formal business plan with market analysis and financial projections. Required for most funding sources.',
        section: 'Business',
        docCategories: ['other'],
        suggestedTags: ['business-plan', 'financial-projections', 'pitch'],
        keywords: ['business plan', 'financial projections', 'pitch deck', 'market analysis', 'pro forma'],
        validation: {},
        weight: 2,
        notApplicableWhen: { seeking_funding: 'false' },
      },
      {
        id: 'biz-trademark',
        title: 'Trademark / IP Registration',
        description: 'Trademark application, copyright registration, or other intellectual property documentation.',
        section: 'Legal',
        docCategories: ['other', 'contract'],
        suggestedTags: ['trademark', 'ip', 'copyright', 'patent'],
        keywords: ['trademark', 'intellectual property', 'copyright', 'patent', 'ip registration'],
        validation: {},
        weight: 1,
      },
    ],
  },

  // =========================================================================
  // 6) Estate Planning / Will Prep
  // =========================================================================
  {
    id: 'estate-planning',
    name: 'Estate Planning / Will Prep',
    description: 'Organize essential documents for will creation, asset protection, and end-of-life planning.',
    icon: 'Scale',
    intakeQuestions: [
      {
        id: 'has_dependents',
        label: 'Do you have minor dependents (children under 18)?',
        type: 'boolean',
      },
      {
        id: 'has_property',
        label: 'Do you own real estate?',
        type: 'boolean',
      },
      {
        id: 'has_business',
        label: 'Do you own a business or have business partnerships?',
        type: 'boolean',
      },
      {
        id: 'has_retirement_accounts',
        label: 'Do you have retirement accounts (401k, IRA, pension)?',
        type: 'boolean',
      },
      {
        id: 'is_married',
        label: 'Are you married or in a domestic partnership?',
        type: 'boolean',
      },
    ],
    requirements: [
      {
        id: 'estate-will',
        title: 'Last Will and Testament',
        description: 'Your current or draft will specifying how assets should be distributed.',
        section: 'Legal',
        docCategories: ['contract', 'other'],
        suggestedTags: ['will', 'testament', 'estate'],
        keywords: ['will', 'testament', 'last will'],
        validation: {},
        weight: 3,
      },
      {
        id: 'estate-poa',
        title: 'Financial Power of Attorney',
        description: 'Durable power of attorney designating someone to manage financial affairs if you become incapacitated.',
        section: 'Legal',
        docCategories: ['contract', 'other'],
        suggestedTags: ['power-of-attorney', 'poa', 'legal'],
        keywords: ['power of attorney', 'poa', 'durable power'],
        validation: {},
        weight: 2,
      },
      {
        id: 'estate-health-directive',
        title: 'Advance Health Care Directive',
        description: 'Living will and/or health care proxy designating medical decision-making authority.',
        section: 'Health',
        docCategories: ['other', 'contract'],
        suggestedTags: ['health-directive', 'living-will', 'healthcare-proxy'],
        keywords: ['health directive', 'living will', 'healthcare proxy', 'advance directive'],
        validation: {},
        weight: 2,
      },
      {
        id: 'estate-beneficiary',
        title: 'Beneficiary Designations (Bank & Insurance)',
        description: 'Documentation of beneficiaries on bank accounts, brokerage accounts, and insurance policies.',
        section: 'Financial',
        docCategories: ['other', 'insurance'],
        suggestedTags: ['beneficiary', 'account'],
        keywords: ['beneficiary', 'designation', 'payable on death', 'pod', 'tod'],
        validation: {},
        weight: 1,
      },
      {
        id: 'estate-retirement-beneficiary',
        title: 'Retirement Account Beneficiary Forms',
        description: 'Beneficiary designation forms for 401(k), IRA, pension, and other retirement accounts.',
        section: 'Financial',
        docCategories: ['other'],
        suggestedTags: ['retirement', 'beneficiary', '401k', 'ira'],
        keywords: ['retirement', 'beneficiary', '401k', 'ira', 'pension', 'retirement beneficiary'],
        validation: {},
        weight: 2,
        notApplicableWhen: { has_retirement_accounts: 'false' },
      },
      {
        id: 'estate-life-insurance',
        title: 'Life Insurance Policies',
        description: 'All current life insurance policies with beneficiary details.',
        section: 'Insurance',
        docCategories: ['insurance'],
        suggestedTags: ['life-insurance'],
        keywords: ['life insurance', 'term life', 'whole life'],
        validation: { notExpired: true, warnExpiringSoon: true },
        weight: 2,
      },
      {
        id: 'estate-property-deeds',
        title: 'Property Deeds / Titles',
        description: 'Deeds, titles, and mortgage documents for all owned real estate.',
        section: 'Property',
        docCategories: ['other', 'contract'],
        suggestedTags: ['deed', 'title', 'property'],
        keywords: ['deed', 'title', 'property', 'real estate', 'mortgage'],
        validation: {},
        weight: 2,
        notApplicableWhen: { has_property: 'false' },
      },
      {
        id: 'estate-guardian',
        title: 'Guardian Designation for Minors',
        description: 'Legal document naming guardian(s) for minor children in case both parents are unable to care for them.',
        section: 'Legal',
        docCategories: ['contract', 'other'],
        suggestedTags: ['guardian', 'minor', 'child'],
        keywords: ['guardian', 'guardianship', 'minor', 'custody'],
        validation: {},
        weight: 3,
        notApplicableWhen: { has_dependents: 'false' },
      },
      {
        id: 'estate-trust',
        title: 'Trust Documents',
        description: 'Revocable living trust, irrevocable trust, or other trust agreements.',
        section: 'Legal',
        docCategories: ['contract', 'other'],
        suggestedTags: ['trust', 'revocable-trust', 'estate'],
        keywords: ['trust', 'revocable trust', 'irrevocable', 'trust agreement'],
        validation: {},
        weight: 1,
      },
      {
        id: 'estate-business-succession',
        title: 'Business Succession Plan',
        description: 'Succession plan, buy-sell agreement, or operating agreement addressing what happens to the business.',
        section: 'Business',
        docCategories: ['contract', 'other'],
        suggestedTags: ['business', 'succession', 'buy-sell'],
        keywords: ['succession plan', 'buy-sell agreement', 'business succession', 'ownership transfer'],
        validation: {},
        weight: 2,
        notApplicableWhen: { has_business: 'false' },
      },
      {
        id: 'estate-marital-agreement',
        title: 'Marital / Partnership Agreement',
        description: 'Prenuptial agreement, postnuptial agreement, or domestic partnership documentation.',
        section: 'Legal',
        docCategories: ['contract', 'other'],
        suggestedTags: ['prenup', 'marital', 'partnership'],
        keywords: ['prenuptial', 'postnuptial', 'marital agreement', 'domestic partnership'],
        validation: {},
        weight: 1,
        notApplicableWhen: { is_married: 'false' },
      },
      {
        id: 'estate-digital-assets',
        title: 'Digital Asset Inventory',
        description: 'List of digital accounts, passwords manager access, cryptocurrency wallets, and online assets.',
        section: 'Financial',
        docCategories: ['other'],
        suggestedTags: ['digital-assets', 'passwords', 'crypto'],
        keywords: ['digital assets', 'passwords', 'cryptocurrency', 'online accounts', 'digital estate'],
        validation: {},
        weight: 1,
      },
      {
        id: 'estate-letter-of-intent',
        title: 'Letter of Intent / Final Wishes',
        description: 'Personal letter describing your wishes for funeral arrangements, organ donation, and messages to loved ones.',
        section: 'Legal',
        docCategories: ['other'],
        suggestedTags: ['letter-of-intent', 'final-wishes', 'funeral'],
        keywords: ['letter of intent', 'final wishes', 'funeral', 'burial', 'organ donation'],
        validation: {},
        weight: 1,
      },
    ],
  },
];

/**
 * Look up a template by ID.
 */
export function getTemplateById(id: string): LifeEventTemplate | undefined {
  return LIFE_EVENT_TEMPLATES.find((t) => t.id === id);
}
