/*
  # Add tags column to documents table

  1. Changes
    - Add `tags` column to `documents` table as a text array
    - Tags will be automatically generated by AI when 60% of chunks have embeddings
    - Maximum of 5 tags per document
    
  2. Notes
    - Tags are stored as an array of strings
    - Default is an empty array
    - Used for categorization and quick filtering
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'documents' AND column_name = 'tags'
  ) THEN
    ALTER TABLE documents ADD COLUMN tags text[] DEFAULT '{}';
  END IF;
END $$;
