/*
  # Update embedding dimensions for local e5-mistral-7b-instruct model

  1. Changes
    - Modify the `embedding` column in `document_chunks` table from vector(384) to vector(4096)
    - Update the `match_document_chunks` function to accept 4096-dimensional embeddings
    - Recreate indexes for optimal performance with larger vectors

  2. Notes
    - e5-mistral-7b-instruct produces 4096-dimensional embeddings
    - Existing 384-dimensional embeddings will be preserved but won't be usable for similarity search
    - Consider re-generating all embeddings with the new model for consistency
    - This change enables much better semantic understanding and search quality
*/

-- Drop existing indexes that depend on the embedding column
DROP INDEX IF EXISTS document_chunks_embedding_idx;

-- Update the embedding column to support 4096 dimensions (e5-mistral-7b-instruct model)
ALTER TABLE document_chunks
ALTER COLUMN embedding TYPE vector(4096);

-- Recreate the embedding index with updated dimensions
-- Using ivfflat for efficient approximate nearest neighbor search
-- Increased lists parameter for larger vector space
CREATE INDEX document_chunks_embedding_idx
ON document_chunks
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 200);

-- Update the match function to accept 4096-dimensional embeddings
CREATE OR REPLACE FUNCTION match_document_chunks(
  query_embedding vector(4096),
  match_document_id uuid,
  match_count int DEFAULT 5,
  similarity_threshold float DEFAULT 0.3
)
RETURNS TABLE (
  id uuid,
  document_id uuid,
  chunk_index int,
  chunk_text text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    dc.id,
    dc.document_id,
    dc.chunk_index,
    dc.chunk_text,
    1 - (dc.embedding <=> query_embedding) as similarity
  FROM document_chunks dc
  WHERE
    dc.document_id = match_document_id
    AND dc.embedding IS NOT NULL
    AND 1 - (dc.embedding <=> query_embedding) >= similarity_threshold
  ORDER BY dc.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Add comment to track migration
COMMENT ON COLUMN document_chunks.embedding IS
  'Vector embedding generated by e5-mistral-7b-instruct (4096 dimensions). Updated on 2026-02-11.';
